# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mercury.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'mercury.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmercury.proto\":\n\x16MercuryMultiGetRequest\x12 \n\x07request\x18\x01 \x03(\x0b\x32\x0f.MercuryRequest\"4\n\x14MercuryMultiGetReply\x12\x1c\n\x05reply\x18\x01 \x03(\x0b\x32\r.MercuryReply\"O\n\x0eMercuryRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\x0c\n\x04\x65tag\x18\x04 \x01(\x0c\"\xed\x01\n\x0cMercuryReply\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x11\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\x12/\n\x0c\x63\x61\x63he_policy\x18\x03 \x01(\x0e\x32\x19.MercuryReply.CachePolicy\x12\x0b\n\x03ttl\x18\x04 \x01(\x11\x12\x0c\n\x04\x65tag\x18\x05 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x06 \x01(\t\x12\x0c\n\x04\x62ody\x18\x07 \x01(\x0c\"@\n\x0b\x43\x61\x63hePolicy\x12\x0c\n\x08\x43\x41\x43HE_NO\x10\x01\x12\x11\n\rCACHE_PRIVATE\x10\x02\x12\x10\n\x0c\x43\x41\x43HE_PUBLIC\x10\x03\"q\n\x06Header\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x13\n\x0bstatus_code\x18\x04 \x01(\x11\x12\x1f\n\x0buser_fields\x18\x06 \x03(\x0b\x32\n.UserField\"\'\n\tUserField\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mercury_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MERCURYMULTIGETREQUEST']._serialized_start=17
  _globals['_MERCURYMULTIGETREQUEST']._serialized_end=75
  _globals['_MERCURYMULTIGETREPLY']._serialized_start=77
  _globals['_MERCURYMULTIGETREPLY']._serialized_end=129
  _globals['_MERCURYREQUEST']._serialized_start=131
  _globals['_MERCURYREQUEST']._serialized_end=210
  _globals['_MERCURYREPLY']._serialized_start=213
  _globals['_MERCURYREPLY']._serialized_end=450
  _globals['_MERCURYREPLY_CACHEPOLICY']._serialized_start=386
  _globals['_MERCURYREPLY_CACHEPOLICY']._serialized_end=450
  _globals['_HEADER']._serialized_start=452
  _globals['_HEADER']._serialized_end=565
  _globals['_USERFIELD']._serialized_start=567
  _globals['_USERFIELD']._serialized_end=606
# @@protoc_insertion_point(module_scope)
